# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca_veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerencia_frota.Marca_veiculo', verbose_name='Marca_Veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='tipo_marca',
            name='id_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerencia_frota.Tipo_Veiculo', verbose_name='Tipo_Veiculo'),
        ),
    ]
