# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia_frota', '0003_tipoveiculo_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoveiculo',
            name='cor',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipoveiculo',
            name='placa',
            field=models.CharField(default=2, max_length=9),
            preserve_default=False,
        ),
    ]
