# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia_frota', '0004_auto_20170329_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipomarca',
            name='id_marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerencia_frota.MarcaVeiculo', verbose_name='MarcaVeiculo'),
        ),
        migrations.AlterField(
            model_name='tipoveiculo',
            name='marca',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gerencia_frota.MarcaVeiculo'),
        ),
    ]
